### ISSUE TITLE
Circle CI concepts

### ISSUE THREAD

**Issue by kapenon** [kapenon/myNote#10]
## ToDo
 - [x] Read https://qiita.com/gold-kou/items/4c7e62434af455e977c2
 - [x] read other 3 articles

## Goal
 - [x] What is Circle CI?
 - [x] Why it's nice?
 - [x] How you can apply it to daily work?

## Docs
Circle CIとは？：
https://qiita.com/gold-kou/items/4c7e62434af455e977c2

Githubとの連携方法：
https://www.tweeeety.blog/entry/2018/02/09/195345

**Comment by kapenon** [comment]
What is Circle CI?
継続的インテグレーション（CI、ビルド・テストを継続的に繰り返す手法。エクストリームプログラミングの一種）を簡単にするSaaS。
使い方は簡単で、CircleCI側でGithubと連携認証するだけ。
PR時にCIをマストで通す設定もGithub側でする

プロジェクトのルートにCI設定ファイルの.CircleCI/config.ymlを置く。
この中に
- テストを走らせるコマンド
- ディレクトリ指定
- どっかーいめーじ（どっかーはぶ、ECR、プライベートなイメージ）を指定
- 条件式
- ファイル操作
：
とか色々かける

CircleCIが全部それらを実行して処理が通れば、PRを出せるようになる

**Comment by kapenon** [comment]
## Why it's nice?
SaaSだからめちゃ楽
Jenkinsと違って自分で専用サーバを立てる必要がない
UIのカスタマイズが不要

**Comment by kapenon** [comment]
## How you can apply it to daily work?

Githubでなら上記の方法でそのまま連携できる
MLOpsに導入できそう
